server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
#数据源的公告属性
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/muxin-app
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  type-aliases-package: com.muxin.app.dao.entry
  mapper-locations: classpath:mapper/*.xml
############################################################
#fastdfs 配置
#fdfs:
  connect-timeout: 601
  so-timeout: 1501
  thumb-image:
    height: 80
    width: 80
  tracker-list:
      - 192.168.1.70:22122

